name: Python application

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: 'dpr-test-app' # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.' # Set this to the path to your web app project, defaults to the repository root
  #STARTUP_COMMAND: 'gunicorn --bind=0.0.0.0 --timeout 600 main:app'
  STARTUP_COMMAND: 'gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 main:app'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install setup
        pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
        echo "Installing Requirements"
        pip install -r requirements.txt
        pip install fastapi uvicorn
        echo "The uvicorn version installed is:"
        uvicorn --version
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        startup-command: ${{ env.STARTUP_COMMAND }}
    - name: logout
      run: |
        az logout
